### ISSUE TITLE
Daily Notes Conflict

### ISSUE THREAD

**Issue by datastring** [Make-md/makemd#116]
Hello,

I am currently getting a weird bug when trying to access my Daily Notes. Obsidian bugs out, and does not open the daily note. I have included a video below showcasing the issue.

## Replicating the Issue

The behaviour/issue can be replicated by trying to access my Daily Notes by clicking the sidebar button, by clicking the day within the Calendar plugin, or by using the command "Open today's daily note".

## Temporary Solution

The only temporary solution that has worked reliably, is disabling MAKE.md in the community plugins.

## Video Showcase

[Video Showcase](https://user-images.githubusercontent.com/108536517/234904629-3f95cac9-c275-43c7-ba2d-43dd61cc0027.mp4)

**Comment by jp-cen** [comment]
Reviewing the video, this issue might not have been addressed by the patch. Let me know it if does not and I will do more investigation on why this is happening.

**Comment by datastring** [comment]
Updated MAKE.md and enabled it again. Unfortunately, the problem still persists.

Curiously, the outline panel starts rapidly changing between files/dates. Sometimes stopping at showing my daily note template's outline instead of the currently open daily note. I added a screenshot showing an example of this.

MAKE.md 0.7.12
Obsidian v1.1.16
Installer v1.0.3

![image](https://user-images.githubusercontent.com/108536517/234988927-e1aa00fc-7a97-4f48-9a7b-9f80ed4191aa.png)

**Comment by datastring** [comment]
I took another video that shows the outline resetting every time I click within the open daily note.

https://user-images.githubusercontent.com/108536517/234990960-671af08a-c9eb-4057-bb22-408b5c9c66e1.mp4

**Comment by jp-cen** [comment]
I'm trying to reproduce the issue. It looks like you don't have Spaces or Contexts enabled for make.md, are you using flow blocks?

**Comment by datastring** [comment]
I took some more video and screenshots of my MAKE.md settings. Hope it offers more information.

## MAKE.md Settings

![Obsidian_mJJR63JXny](https://user-images.githubusercontent.com/108536517/235003767-c6d476ab-f692-4655-ae4d-dc67e22b995a.png)

![Obsidian_m1m8oGHp9I](https://user-images.githubusercontent.com/108536517/235003766-cb359fd1-0319-467b-849d-13327e8c9316.png)

![Obsidian_j2rjuVBHEY](https://user-images.githubusercontent.com/108536517/235003762-a7bcc521-5934-4b82-a1de-110b2cf932f2.png)

## Showcase Video

https://user-images.githubusercontent.com/108536517/235003079-fbe8304a-d630-4b2c-9815-aba1fd3df856.mp4

**Comment by jp-cen** [comment]
Thanks I was able to track this to an incompatibility with Hover Editor. Let me know if you have that plugin enabled. Unfortunately after extensively looking into Hover Editor today and yesterday, there's no way for the flow block from make.md to be compatible with hover editor. However, a compatibility mode will be added as well as a hover editor replacement to preserve the same workflow. Thanks for the detailed videos and images for helping tracking this issue down!

**Comment by datastring** [comment]
Incredible! I did have it enabled. The issue was resolved after disabling Hover Editor.

Thank you. I really appreciate your care for others' time. Take care.

**Comment by kafkazov** [comment]
same problem. hover editer.
