### ISSUE TITLE
Latest update deleted two spaces

### ISSUE THREAD

**Issue by jpmoo** [Make-md/makemd#515]
Upon the latest update, I lost access to two spaces in my focus.

One is for my daily notes (Dailies) and the other is for people (People). Both are in simple folders at the root level of the vault.

When I started Obsidian after the update, both of these appeared in my focus list, by could not be expanded. Then, they just both disappeared. When I go to re-add them, they do not appear on the list. When I click to add them as a new space, nothing happens.

I've flushed the "Space" folder our of both of these folders, but it hasn't helped before trying to remake them, but it doesn't help. It's like Make.md can't even see the folders anymore.

I also manually tried to remove and add them to the waypoints.json file in the Space folder of the vault, but that doesn't help either.

How do I get these back?!?!?

**Comment by jpmoo** [comment]
Vertical. They’d be listed as two other Spaces there: People and Dailies.

**Comment by jpmoo** [comment]
Fixed it! But not 100% sure how. I went into the plugin folder's data.json file and found these two folders listed both in hiddenFiles and expandedSpaces. Removed them from those lists (there were several of each) and the two spaces popped back into place and are working properly.

**Comment by jp-cen** [comment]
Good to hear! The update fixed hidden files still showing up, so that’s most likely the reason
